server:
  port: 8085
  
  
spring:
  application:
    name: ConfigServer
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/himanshu6521/EcommerceProductCatalog-ConfigServer
          clone-on-start: true      